name: Shell Commands

on: [push]

jobs: 
  run_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo "Hello World"
      - name: Multi-line script
        run: |
          node -v
          npm -v
      - name: Python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run_windows_commands:
    runs-on: windows-latest
    needs: ["run_commands"]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash

